### ISSUE TITLE
Error: rosbridge and python-tornado

### ISSUE THREAD

**Issue by capitalPSA** [RobotWebTools/roslibjs#329]
I am receiving the following error when running the simple.html file in the examples folder after following the installation instructions in the CONTRIBUTING.md file:

    [ERROR] [1554133353.748381]: Traceback (most recent call last):
    File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbridge_server/websocket_handler.py", line 168, in prewrite_message yield self.write_message(message, binary)
    File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run value = future.result()
    File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result raise_exc_info(self._exc_info)
    File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 956, in handle_yield self.future = convert_yielded(yielded)
    File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1026, in convert_yielded raise BadYieldError("yielded unknown object %r" % (yielded,))
    BadYieldError: yielded unknown object None    

ROS: Kinetic
Ubuntu: 16.04
Python: 2.7.12
Python-tornado: 4.2.1-1ubuntu3
Python-future: 0.15.2-1

Is there a library incompatibility?

**Comment by capitalPSA** [comment]
My apologies. There is another git repo responsible for this issue. See: https://github.com/RobotWebTools/rosbridge_suite/issues/394

(Right user, wrong repo).

**Comment by capitalPSA** [comment]
Closing now.
